name: Release Please

on:
  push:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always
  CRATE_NAME: asfald
  RUST_BACKTRACE: 1
  GITHUB_TOKEN: ${{ github.token }}

jobs:
  release-please:
    runs-on: ubuntu-latest

    permissions:
      issues: write
      contents: write
      packages: write
      pull-requests: write

    outputs:
      release_created: ${{ steps.release.outputs.release_created }}
      tag_name: ${{ steps.release.outputs.tag_name }}
    steps:
      - uses: googleapis/release-please-action@v4
        id: release
        with:
          release-type: rust

  build-release:
    needs: release-please
    if: ${{ needs.release-please.outputs.release_created == 'true' }}
    uses: ./.github/workflows/ci.yml

  make-release:
    name: Make release
    runs-on: ubuntu-latest
    needs: [release-please, build-release]
    if: success() && ${{ needs.release-please.outputs.release_created == 'true' }}
    steps:
      - uses: actions/download-artifact@v4
        with:
          path: ./binaries
      - name: Display structure of downloaded files
        run: ls -R ./binaries
      - name: Generate artifacts names
        run: |
          cd ./binaries
          mkdir -p ./artifacts
          for dir in */; do
            name="${dir%/}"
            mv "$dir/asfald" "artifacts/$name"
          done
      - uses: softprops/action-gh-release@v1
        with:
          files: ./binaries/artifacts/*
          fail_on_unmatched_files: true
          tag_name: ${{ needs.release-please.outputs.tag_name }}
